In [2]:
import pandas as pd

In [15]:
comprobantes = pd.read_excel('Comprobantes detallados.xlsx', header=7)
comprobantes.head(10)

,Secuencia,Fecha elaboración,Código contable,Cuenta contable,Identificación,Sucursal,Nombre tercero,Descripción,Detalle,Centro de costo,Débito,Crédito
0,Comprobante: A-376,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,791634.31,791634.31
1,1,07/02/2026,14350101.0,Mercancías no fabricadas,901678785.0,0.0,PROVEEDORA ELECTRICA NACIONAL SAS,C. 12AWG CU ROJO THHN-2 600V ROLLO X 100,Prod: NX10011765 Cant: 1.00,NaN,0.00,199730.25
2,2,07/02/2026,61350520.0,Ajuste de Inventarió,901678785.0,0.0,PROVEEDORA ELECTRICA NACIONAL SAS,Ajuste de Inventarió,NaN,NaN,199730.25,0.00
3,3,07/02/2026,14350101.0,Mercancías no fabricadas,901678785.0,0.0,PROVEEDORA ELECTRICA NACIONAL SAS,C. 12AWG CU ROJO THHN-2 600V X MT,Prod: NX10024729 Cant: 100.00,NaN,200670.00,0.00
4,4,07/02/2026,61350520.0,Ajuste de Inventarió,901678785.0,0.0,PROVEEDORA ELECTRICA NACIONAL SAS,Ajuste de Inventarió,NaN,NaN,0.00,200670.00
5,5,07/02/2026,14350101.0,Mercancías no fabricadas,901678785.0,0.0,PROVEEDORA ELECTRICA NACIONAL SAS,C. 12AWG CU VERDE THHN-2 600V ROLLO X 100,Prod: NX10011767 Cant: 1.00,NaN,0.00,199072.06
6,6,07/02/2026,61350520.0,Ajuste de Inventarió,901678785.0,0.0,PROVEEDORA ELECTRICA NACIONAL SAS,Ajuste de Inventarió,NaN,NaN,199072.06,0.00
7,7,07/02/2026,14350101.0,Mercancías no fabricadas,901678785.0,0.0,PROVEEDORA ELECTRICA NACIONAL SAS,C. 12AWG CU VERDE THHN-2 600V X MT,Prod: NX10024731 Cant: 100.00,NaN,192162.00,0.00
8,8,07/02/2026,61350520.0,Ajuste de Inventarió,901678785.0,0.0,PROVEEDORA ELECTRICA NACIONAL SAS,Ajuste de Inventarió,NaN,NaN,0.00,192162.00
9,Comprobante: A-377,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1396.07,1396.07

In [16]:
# Extraer código de comprobante de las filas encabezado y propagarlo
comprobantes['Comprobante'] = comprobantes['Secuencia'].where(
    comprobantes['Secuencia'].astype(str).str.startswith('Comprobante:')
).ffill()

# Extraer solo el código (ej: "A-376" de "Comprobante: A-376")
comprobantes['Comprobante'] = comprobantes['Comprobante'].str.replace('Comprobante: ', '', regex=False)

# Eliminar las filas encabezado de comprobante (quedan solo las secuencias)
comprobantes = comprobantes[~comprobantes['Secuencia'].astype(str).str.startswith('Comprobante:')].reset_index(drop=True)

# Crear columna Movimiento: crédito cuando débito es 0, -débito cuando crédito es 0
comprobantes['Movimiento'] = comprobantes.apply(
    lambda r: r['Crédito'] if r['Débito'] == 0 else -r['Débito'], axis=1
)

# Mover Comprobante al inicio del dataframe
cols = ['Comprobante'] + [c for c in comprobantes.columns if c != 'Comprobante']
comprobantes = comprobantes[cols]

comprobantes.head(20)

,Comprobante,Secuencia,Fecha elaboración,Código contable,Cuenta contable,Identificación,Sucursal,Nombre tercero,Descripción,Detalle,Centro de costo,Débito,Crédito,Movimiento
0,A-376,1,07/02/2026,14350101.0,Mercancías no fabricadas,901678785.0,0.0,PROVEEDORA ELECTRICA NACIONAL SAS,C. 12AWG CU ROJO THHN-2 600V ROLLO X 100,Prod: NX10011765 Cant: 1.00,NaN,0.00,199730.25,199730.25
1,A-376,2,07/02/2026,61350520.0,Ajuste de Inventarió,901678785.0,0.0,PROVEEDORA ELECTRICA NACIONAL SAS,Ajuste de Inventarió,NaN,NaN,199730.25,0.00,-199730.25
2,A-376,3,07/02/2026,14350101.0,Mercancías no fabricadas,901678785.0,0.0,PROVEEDORA ELECTRICA NACIONAL SAS,C. 12AWG CU ROJO THHN-2 600V X MT,Prod: NX10024729 Cant: 100.00,NaN,200670.00,0.00,-200670.00
3,A-376,4,07/02/2026,61350520.0,Ajuste de Inventarió,901678785.0,0.0,PROVEEDORA ELECTRICA NACIONAL SAS,Ajuste de Inventarió,NaN,NaN,0.00,200670.00,200670.00
4,A-376,5,07/02/2026,14350101.0,Mercancías no fabricadas,901678785.0,0.0,PROVEEDORA ELECTRICA NACIONAL SAS,C. 12AWG CU VERDE THHN-2 600V ROLLO X 100,Prod: NX10011767 Cant: 1.00,NaN,0.00,199072.06,199072.06
5,A-376,6,07/02/2026,61350520.0,Ajuste de Inventarió,901678785.0,0.0,PROVEEDORA ELECTRICA NACIONAL SAS,Ajuste de Inventarió,NaN,NaN,199072.06,0.00,-199072.06
6,A-376,7,07/02/2026,14350101.0,Mercancías no fabricadas,901678785.0,0.0,PROVEEDORA ELECTRICA NACIONAL SAS,C. 12AWG CU VERDE THHN-2 600V X MT,Prod: NX10024731 Cant: 100.00,NaN,192162.00,0.00,-192162.00
7,A-376,8,07/02/2026,61350520.0,Ajuste de Inventarió,901678785.0,0.0,PROVEEDORA ELECTRICA NACIONAL SAS,Ajuste de Inventarió,NaN,NaN,0.00,192162.00,192162.00
8,A-377,1,09/02/2026,14350101.0,Mercancías no fabricadas,901678785.0,0.0,PROVEEDORA ELECTRICA NACIONAL SAS,CINTA ALISLANTE NEGRA 15 MTS GRANDE UL FMX VL ...,Prod: KL-1227 Cant: 0.00,NaN,0.00,1396.07,1396.07
9,A-377,2,09/02/2026,61350515.0,"Retiro de inventario para activos fijos, consu...",901678785.0,0.0,PROVEEDORA ELECTRICA NACIONAL SAS,"Retiro de inventario para activos fijos, consu...",NaN,NaN,1396.07,0.00,-1396.07
10,A-378,1,10/02/2026,14350101.0,Mercancías no fabricadas,901678785.0,0.0,PROVEEDORA ELECTRICA NACIONAL SAS,CABLE UTP INTERIOR COBRE CAT 5E ANCLA ROLLO,Prod: 90105 Cant: 1.00,NaN,0.00,923860.00,923860.00
11,A-378,2,10/02/2026,61350520.0,Ajuste de Inventarió,901678785.0,0.0,PROVEEDORA ELECTRICA NACIONAL SAS,Ajuste de Inventarió,NaN,NaN,923860.00,0.00,-923860.00
12,A-378,3,10/02/2026,14350101.0,Mercancías no fabricadas,901678785.0,0.0,PROVEEDORA ELECTRICA NACIONAL SAS,CABLE UTP INTERIOR COBRE CAT 5E ANCLA POR METRO,Prod: 90105C Cant: 305.00,NaN,281777.30,0.00,-281777.30
13,A-378,4,10/02/2026,61350520.0,Ajuste de Inventarió,901678785.0,0.0,PROVEEDORA ELECTRICA NACIONAL SAS,Ajuste de Inventarió,NaN,NaN,0.00,281777.30,281777.30
14,CC-1-1462,1,02/02/2026,22050501.0,Proveedores nacionales,901144843.0,0.0,BOGOTA LIMPIA S.A.S. E.S.P.,Proveedores nacionales,FSP-11827580017 Cuota: 1 Fecha: 02/02/2026,NaN,156810.00,0.00,-156810.00
15,CC-1-1462,2,02/02/2026,22050501.0,Proveedores nacionales,899999094.0,0.0,EMPRESA DE ACUEDUCTO Y ALCANTARILLADO DE BOGOT...,Proveedores nacionales,FSP-11827580017 Cuota: 1 Fecha: 27/01/2026,NaN,112070.00,0.00,-112070.00
16,CC-1-1462,3,02/02/2026,11100504.0,BOLD 170013272354,899999094.0,0.0,EMPRESA DE ACUEDUCTO Y ALCANTARILLADO DE BOGOT...,BOLD 170013272354,NaN,NaN,0.00,268880.00,268880.00
17,CC-1-1463,1,04/02/2026,13652002.0,Prestamos (Otros),24757647.0,0.0,Olga Rosio Gomez Ramirez,PAGO GAS SRA BILMA,NaN,NaN,33720.00,0.00,-33720.00
18,CC-1-1463,2,04/02/2026,11050503.0,Daviplata,24757647.0,0.0,Olga Rosio Gomez Ramirez,PAGO GAS SRA BILMA,NaN,NaN,0.00,33720.00,33720.00
19,CC-1-1466,1,09/02/2026,13652002.0,Prestamos (Otros),24757647.0,0.0,Olga Rosio Gomez Ramirez,PEDIDO PULSERA,NaN,NaN,86000.00,0.00,-86000.00